version: "3.7"

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  backend:
    environment:
      - NODE_PORT=${NODE_PORT}
      - NODE_ENV=${NODE_ENV}
      - FIXER_KEY=${FIXER_KEY}
      - FIXER_URL=${FIXER_URL}
      - IPAPI_URL=${IPAPI_URL}
      - REDIS_URL= redis://redis:6379
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ip-challenge-api
    volumes:
      - ./src:/home/node/app/src
      - ./:/home/node/app/nodemon.json
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm run watch-server
volumes:
  redis:
    driver: local
